name: CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r app/requirements.txt
        pip install pytest
    - name: Run tests
      run: |
        pytest app/tests/
    - name: Install Podman  # Using Podman instead of Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y podman
    - name: Build container image
      run: podman build -t myapp:${{ github.sha }} .
